[versions]
junit = "5.9.2"
junit-platform-launcher = "1.9.2"
strikt = "0.34.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.20" }